### ISSUE TITLE
Fail to build amx

### ISSUE THREAD

**Issue by peyer** [yvt/amx-rs#2]
![image](https://user-images.githubusercontent.com/19945545/133805333-37774575-76cb-4773-ac48-f508a1ef2fd9.png)

**Comment by yvt** [comment]
This inline assembler doesn't compile on x86_64 because `.word` implies a different size than in AArch64. (Note that AMX instructions are only exposed in AArch64, not in x86_64.)

Fixed in 826c92f0e68caf58e5433e22ccce63c34da1697a by disabling the compilation of the native interface (`crate::nativeops`) on a target ISA that definitely doesn't support the AMX instructions.

**Comment by peyer** [comment]
Thanks! I truly compiled source code on x86_64 mac without m1 chip.
Another question, dose apple 11/12 support asm code for calling amx coprocessor with xcode?

**Comment by yvt** [comment]
If you mean Apple A11 and A12, their CPUs don't support AMX according to <https://news.ycombinator.com/item?id=24472004>:

> Apple A13 adds AMX, a set of (mostly) AI acceleration instructions that are also useful for matrix math in general.

They have Neural Engine, though.

In case you are developing an app, you might also keep in mind that using undocumented instructions directly has a high risk of App Store rejection. `Accelerate.framework` (and Core ML, maybe?) is the only supported way to utilize AMX.
